### ISSUE TITLE
compatibility with app router

### ISSUE THREAD

**Issue by timconnorz** [remcohaszing/recma-nextjs-static-props#2]
Thanks for making this plugin! Im excited to use it. 

I have been trying for several hours now to try and get metadata to load into my html <head> element on my blog pages. I think maybe this plugin will finally unlock this for me.

Is this compatible with the app router set up of nextjs? I ask because i have the plugin set up but im not able to access the exported variables in my layout.tsx file. Would be helpful to know if what I'm trying is simply not possible because im using the app router.

in app/layout.tsx i have 
```ts
export default function RootLayout({ children, ...props }: LayoutProps) {
  console.log("root layout", props)
```

in app/posts/test/page.mdx i have
```
export const description = 'This is my document'

# hello
friend
```

in next.config.mjs i have
```ts
import nextMDX from '@next/mdx';
// other imports....
import recmaNextjsStaticProps from 'recma-nextjs-static-props'

const withMDX = nextMDX({
  extension: /\.mdx?$/,
  options: {
    remarkPlugins: [
      remarkFrontmatter,
      remarkBreaks, 
      remarkGfm,
    ],
    rehypePlugins: [rehypeHighlight],
    recmaPlugins: [recmaNextjsStaticProps],
  },
});

const nextConfig = {
  pageExtensions: ['js', 'jsx', 'mdx', 'ts', 'tsx'],
  experimental: {
    mdxRs: false, 
  }
};

export default withMDX(nextConfig);

```

when i examine the logs for my pages i see:
```
root layout { params: {} }
```

**Comment by remcohaszing** [comment]
I’m glad you like this plugin. :)

I would love to support the Next.js app directory, but I’m not sure how. What would it look like?

`pages/_app` supports `pageProps`. These `pageProps` can be created from a page using `getStaticProps`. What’s a similar construct to get variables from a `page` file to a `layout` component in the `app` directory?

**Comment by remcohaszing** [comment]
I asked @karlhorky for feedback on this, to try and figure out what’s technically possible. Thanks for helping out :heart: 

It appears to be technically impossible to get props from a `page` into a `layout`.

If you goal is to specify page metadata, you can do so by exporting the [`metadata`](https://nextjs.org/docs/app/building-your-application/optimizing/metadata) object:

```mdx
{/* app/posts/test/page.mdx */}

{/** @type {import('next').Metadata} */}
export const metadata = {
  description: 'This is my document'
}

# hello
friend
```

If you need to use this data for something more advanced, you can use custom logic based on the provided [Next functions](https://nextjs.org/docs/app/api-reference/functions) to resolve your file from the layout, and import it.

```ts
// app/layout.ts

export default async function Layout(props) {
  const path = resolvePagePath(props)
  const { description } = await import(path)
}
```

Some additional resources:

- https://medium.com/@kcabading/creating-a-breadcrumb-component-in-a-next-js-app-router-a0ea24cdb91a
- https://github.com/vercel/next.js/issues/43704#issuecomment-1729964730
- https://github.com/vercel/next.js/issues/43704#issuecomment-1716872199

I’m closing this issue, because it’s currently not technically possible to support this. If this ever becomes possible in the future, or someone has a good idea to support this, I’m open to suggestions.

**Comment by timconnorz** [comment]
Thanks so much for your response! I appreciate you looking into it just to help out an internet stranger. 

I'll try your suggestion :)
